{
  config,
  lib,
  pkgs,
  ...
}:

{
  # This file will be generated by nixos-anywhere during installation
  # For now, it's a placeholder to satisfy the import in configuration.nix

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
